### ISSUE TITLE
Support msbuild project item metadata Visible=false to be displayed when "Show all items" is checked

### ISSUE THREAD

**Issue by abpiskunov** [Microsoft/VSProjectSystem#67] opened 2015-09-08 18:25 UTC
Currently if our project would have items with Visible=false metadata , those items would be not visible in Solution Explorer nor in normal view neither when "Show all Files " is checked. 

Csproj projects do show Visible=false files when "Show all files" is checked, CPS should also follow same logic.

**Comment by lifengl** [comment] 2015-09-17 21:23
It looks CSharp just ignore all those items inside msbuild project, so the file will be shown as an excluded file, when "show all files" is checked.  The "Include in project" command is enabled. That doesn't seem to be the behavior we want.  

We will fix our behavior into this way:
1, visible=false items will be visible, when it has a physical file item, and show all files is checked.
2, those items will stay invisible, when it has no physical file behind, even show all files is checked. (C# project use special project items to represent platforms, which are not file items at all, we don't want to show them in the explorer.)

**Comment by abpiskunov** [comment] 2015-09-17 22:15
"those items will stay invisible, when it has no physical file behind" - just want to make sure that folders (and empty folders would work there too

**Comment by lifengl** [comment] 2015-09-22 00:01
The issue is expected to be fixed in the update 1 release.

**Closed by lifengl** 2015-09-22 00:01 UTC
