### ISSUE TITLE
VS2017 Extensibility Preview - Value does not fall within expected range

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#177] opened 2017-02-12 14:34 UTC
When adding a new command to my project (Add New Item --> Custom Command) it attempts to add it tot he project, but then I get this error:

![image](https://cloud.githubusercontent.com/assets/3176632/22862970/52145f80-f130-11e6-8e84-bc8ab5ade44f.png)

**Comment by adrianvmsft** [comment] 2017-02-22 00:55
I am not seeing this problem using a new project type created using the latest internal build of the project system extensibility.
I wonder if this was a symptom of the other issues you encountered in your project type that you reported as #178?

**Comment by adrianvmsft** [comment] 2017-02-22 02:48
It turns out it is caused by a VS SDK issue (tracked internally via bug 376552), that happens when the VSIX contains a XAML file included as `Page`.
**Workaround** Make sure the project doesn't contain any XAML files included using the `Page` tag; use `XamlPropertyRule` or `None` if .cs file generation is not desired).

By default, the VSProjectSystemExtensibility project template mistakenly includes general.browseobject.xaml using `Page` - tracked via #171

**Comment by dazinator** [comment] 2017-02-26 16:16
Ah yep that makes sense, nice detective work.

**Comment by adrianvmsft** [comment] 2017-02-27 18:32
Thanks!
I am closing this item as the VS SDK bug is already tracked in the internally, and on the Project System Extensibility side, we have a pending fix for #171.

**Closed by adrianvmsft** 2017-02-27 18:32 UTC
Labels: external, sdk, VS SDK, workaround
